.PHONY: clean All

All:
	@echo "----------Building project:[ cpp_memory - Debug ]----------"
	@"$(MAKE)" -f  "cpp_memory.mk"
clean:
	@echo "----------Cleaning project:[ cpp_memory - Debug ]----------"
	@"$(MAKE)" -f  "cpp_memory.mk" clean
